### ISSUE TITLE
Double tapping answers crashes app

### ISSUE THREAD

**Issue by Aon-Sao** [machiav3lli/DerDieDas#18] opened 2021-08-01 19:00 UTC
Running Android 8.1
I think I have the 2.0.1 version of the app
To reproduce, enter practice mode. 
Tap any article
While the red and green colors are displayed, before the screen proceeds to the next word, again tap any article. 
The app then stops. 
When the app is restarted it says I have fully learned all the words.

**Comment by machiav3lli** [comment] 2021-08-01 23:59
Duplicate of #15, already fixed

**Closed by machiav3lli** 2021-08-01 23:59 UTC
